### PR TITLE
Add twilio notifier

### PR DESCRIPTION
**Pull request by lockshaw**
Is there interest in this feature? I just implemented it for my own personal use, but if there's interest in merging it into the project I'll gladly add tests in the next few days.

### CODE REVIEW

**Comment by helix90** [comment]
+1 for interested.

**Comment by peterdemin** [comment]
That would be awesome!

**Comment by lockshaw** [comment]
Great! I'll add tests

**Comment by peterdemin** [comment]
Taking over in #137

**Pull request closed without merging**
