### PR TITLE
Migrate CI to GitHub Action

### PR DESCRIPTION
**Pull request by egvimo**
I've created two separate workflows. One for tests and one for release.

Releases are only created if a Git tag is pushed. For the release to work, repository secrets have to be created with the Dockerhub credentials: Username, Password and Token (see the workflow for naming). Unfortunately both password and token has to be present, because the Actions require them. The release [looks like this](https://hub.docker.com/r/egvimo/kibitzr).

The test workflow always runs. Currently they are failing, but not always (I don't know why). Here is an example on a successful run (Python 3.7):

```plain
  pytest
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.12/x64/lib
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
============================= test session starts ==============================
platform linux -- Python 3.7.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/runner/work/kibitzr/kibitzr
plugins: mock-3.6.1, cov-3.0.0, pep8-1.0.6
collected 75 items

tests/simulation/test_fetcher.py ........                                [ 10%]
tests/simulation/test_forms.py .                                         [ 12%]
tests/unit/test_app.py ...                                               [ 16%]
tests/unit/test_conf.py .....                                            [ 22%]
tests/unit/test_timeline.py ..........                                   [ 36%]
tests/unit/fetchers/test_script.py ........                              [ 46%]
tests/unit/notifiers/test_bash.py ..                                     [ 49%]
tests/unit/notifiers/test_gotify.py ...                                  [ 53%]
tests/unit/notifiers/test_mailgun.py .                                   [ 54%]
tests/unit/notifiers/test_python.py ..                                   [ 57%]
tests/unit/notifiers/test_smtp.py ....                                   [ 62%]
tests/unit/notifiers/test_stash.py .                                     [ 64%]
tests/unit/notifiers/test_webhook.py .                                   [ 65%]
tests/unit/transforms/test_changes.py ...                                [ 69%]
tests/unit/transforms/test_html.py ....                                  [ 74%]
tests/unit/transforms/test_jinja.py ......                               [ 82%]
tests/unit/transforms/test_json.py .                                     [ 84%]
tests/unit/transforms/test_script.py .....                               [ 90%]
tests/unit/transforms/test_xpath.py .......                              [100%]

=============================== warnings summary ===============================
tests/simulation/test_fetcher.py::test_browser_xpath
  /home/runner/work/kibitzr/kibitzr/kibitzr/transformer/xpath.py:17: DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.
    from defusedxml import lxml as dlxml

tests/simulation/test_fetcher.py::test_scenario
  /home/runner/work/kibitzr/kibitzr/kibitzr/fetcher/browser/launcher.py:60: DeprecationWarning: use options instead of firefox_options
    firefox_options=firefox_options,

tests/simulation/test_fetcher.py::test_scenario
  /home/runner/work/kibitzr/kibitzr/kibitzr/fetcher/browser/fetcher.py:216: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    if isinstance(scenario, collections.Mapping):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================= 75 passed, 3 warnings in 12.94s ========================
```

Here is an example of a failed run (again Python 3.7):

```plain
  pytest
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.12/x64/lib
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
============================= test session starts ==============================
platform linux -- Python 3.7.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/runner/work/kibitzr/kibitzr
plugins: mock-3.6.1, cov-3.0.0, pep8-1.0.6
collected 75 items

tests/simulation/test_fetcher.py ........                                [ 10%]
tests/simulation/test_forms.py F                                         [ 12%]
tests/unit/test_app.py ...                                               [ 16%]
tests/unit/test_conf.py .....                                            [ 22%]
tests/unit/test_timeline.py ..........                                   [ 36%]
tests/unit/fetchers/test_script.py ........                              [ 46%]
tests/unit/notifiers/test_bash.py ..                                     [ 49%]
tests/unit/notifiers/test_gotify.py ...                                  [ 53%]
tests/unit/notifiers/test_mailgun.py .                                   [ 54%]
tests/unit/notifiers/test_python.py ..                                   [ 57%]
tests/unit/notifiers/test_smtp.py ....                                   [ 62%]
tests/unit/notifiers/test_stash.py .                                     [ 64%]
tests/unit/notifiers/test_webhook.py .                                   [ 65%]
tests/unit/transforms/test_changes.py ...                                [ 69%]
tests/unit/transforms/test_html.py ....                                  [ 74%]
tests/unit/transforms/test_jinja.py ......                               [ 82%]
tests/unit/transforms/test_json.py .                                     [ 84%]
tests/unit/transforms/test_script.py .....                               [ 90%]
tests/unit/transforms/test_xpath.py .......                              [100%]

=================================== FAILURES ===================================
____________________________ test_fill_form_sample _____________________________

target = ('127.0.0.1', 17261)

    def test_fill_form_sample(target):
        conf = {
            'name': 'Test page',
            'url': "http://{0}:{1}/form.html".format(*target),
            'form': [
                {'id': 'name', 'value': '{{ "name" | sort | join("") }}'},
                {'css': '#pass', 'creds': 'pass'}
            ],
            # 'scenario': 'import pdb; pdb.set_trace()',
            'transform': [{'css': '.unclosed-tag > #params'}, 'text'],
            # 'headless': False,
        }
>       ok, content = Checker(conf).check()

tests/simulation/test_forms.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
kibitzr/checker.py:41: in check
    ok, report = self.transform(ok, content)
kibitzr/transformer/factory.py:52: in run_pipeline
    ok, content = transform(content)
kibitzr/transformer/html.py:55: in transform
    return method(content)
kibitzr/transformer/html.py:27: in css_selector
    with soup(html) as doc:
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/contextlib.py:112: in __enter__
    return next(self.gen)
kibitzr/transformer/html.py:72: in soup
    yield BeautifulSoup(html, "html.parser")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'<class 'bs4.BeautifulSoup'>' object has no attribute 'contents'") raised in repr()] BeautifulSoup object at 0x7f636d150d90>
markup = None, features = ['html.parser']
builder = <bs4.builder._htmlparser.HTMLParserTreeBuilder object at 0x7f636d150e10>
parse_only = None, from_encoding = None, exclude_encodings = None
element_classes = None, kwargs = {}
deprecated_argument = <function BeautifulSoup.__init__.<locals>.deprecated_argument at 0x7f636d154e60>
original_builder = None, original_features = 'html.parser'
builder_class = <class 'bs4.builder._htmlparser.HTMLParserTreeBuilder'>

    def __init__(self, markup="", features=None, builder=None,
                 parse_only=None, from_encoding=None, exclude_encodings=None,
                 element_classes=None, **kwargs):
        """Constructor.
    
        :param markup: A string or a file-like object representing
         markup to be parsed.
    
        :param features: Desirable features of the parser to be
         used. This may be the name of a specific parser ("lxml",
         "lxml-xml", "html.parser", or "html5lib") or it may be the
         type of markup to be used ("html", "html5", "xml"). It's
         recommended that you name a specific parser, so that
         Beautiful Soup gives you the same results across platforms
         and virtual environments.
    
        :param builder: A TreeBuilder subclass to instantiate (or
         instance to use) instead of looking one up based on
         `features`. You only need to use this if you've implemented a
         custom TreeBuilder.
    
        :param parse_only: A SoupStrainer. Only parts of the document
         matching the SoupStrainer will be considered. This is useful
         when parsing part of a document that would otherwise be too
         large to fit into memory.
    
        :param from_encoding: A string indicating the encoding of the
         document to be parsed. Pass this in if Beautiful Soup is
         guessing wrongly about the document's encoding.
    
        :param exclude_encodings: A list of strings indicating
         encodings known to be wrong. Pass this in if you don't know
         the document's encoding but you know Beautiful Soup's guess is
         wrong.
    
        :param element_classes: A dictionary mapping BeautifulSoup
         classes like Tag and NavigableString, to other classes you'd
         like to be instantiated instead as the parse tree is
         built. This is useful for subclassing Tag or NavigableString
         to modify default behavior.
    
        :param kwargs: For backwards compatibility purposes, the
         constructor accepts certain keyword arguments used in
         Beautiful Soup 3. None of these arguments do anything in
         Beautiful Soup 4; they will result in a warning and then be
         ignored.
    
         Apart from this, any keyword arguments passed into the
         BeautifulSoup constructor are propagated to the TreeBuilder
         constructor. This makes it possible to configure a
         TreeBuilder by passing in arguments, not just by saying which
         one to use.
        """
        if 'convertEntities' in kwargs:
            del kwargs['convertEntities']
            warnings.warn(
                "BS4 does not respect the convertEntities argument to the "
                "BeautifulSoup constructor. Entities are always converted "
                "to Unicode characters.")
    
        if 'markupMassage' in kwargs:
            del kwargs['markupMassage']
            warnings.warn(
                "BS4 does not respect the markupMassage argument to the "
                "BeautifulSoup constructor. The tree builder is responsible "
                "for any necessary markup massage.")
    
        if 'smartQuotesTo' in kwargs:
            del kwargs['smartQuotesTo']
            warnings.warn(
                "BS4 does not respect the smartQuotesTo argument to the "
                "BeautifulSoup constructor. Smart quotes are always converted "
                "to Unicode characters.")
    
        if 'selfClosingTags' in kwargs:
            del kwargs['selfClosingTags']
            warnings.warn(
                "BS4 does not respect the selfClosingTags argument to the "
                "BeautifulSoup constructor. The tree builder is responsible "
                "for understanding self-closing tags.")
    
        if 'isHTML' in kwargs:
            del kwargs['isHTML']
            warnings.warn(
                "BS4 does not respect the isHTML argument to the "
                "BeautifulSoup constructor. Suggest you use "
                "features='lxml' for HTML and features='lxml-xml' for "
                "XML.")
    
        def deprecated_argument(old_name, new_name):
            if old_name in kwargs:
                warnings.warn(
                    'The "%s" argument to the BeautifulSoup constructor '
                    'has been renamed to "%s."' % (old_name, new_name))
                value = kwargs[old_name]
                del kwargs[old_name]
                return value
            return None
    
        parse_only = parse_only or deprecated_argument(
            "parseOnlyThese", "parse_only")
    
        from_encoding = from_encoding or deprecated_argument(
            "fromEncoding", "from_encoding")
    
        if from_encoding and isinstance(markup, str):
            warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
            from_encoding = None
    
        self.element_classes = element_classes or dict()
    
        # We need this information to track whether or not the builder
        # was specified well enough that we can omit the 'you need to
        # specify a parser' warning.
        original_builder = builder
        original_features = features
    
        if isinstance(builder, type):
            # A builder class was passed in; it needs to be instantiated.
            builder_class = builder
            builder = None
        elif builder is None:
            if isinstance(features, str):
                features = [features]
            if features is None or len(features) == 0:
                features = self.DEFAULT_BUILDER_FEATURES
            builder_class = builder_registry.lookup(*features)
            if builder_class is None:
                raise FeatureNotFound(
                    "Couldn't find a tree builder with the features you "
                    "requested: %s. Do you need to install a parser library?"
                    % ",".join(features))
    
        # At this point either we have a TreeBuilder instance in
        # builder, or we have a builder_class that we can instantiate
        # with the remaining **kwargs.
        if builder is None:
            builder = builder_class(**kwargs)
            if not original_builder and not (
                    original_features == builder.NAME or
                    original_features in builder.ALTERNATE_NAMES
            ) and markup:
                # The user did not tell us which TreeBuilder to use,
                # and we had to guess. Issue a warning.
                if builder.is_xml:
                    markup_type = "XML"
                else:
                    markup_type = "HTML"
    
                # This code adapted from warnings.py so that we get the same line
                # of code as our warnings.warn() call gets, even if the answer is wrong
                # (as it may be in a multithreading situation).
                caller = None
                try:
                    caller = sys._getframe(1)
                except ValueError:
                    pass
                if caller:
                    globals = caller.f_globals
                    line_number = caller.f_lineno
                else:
                    globals = sys.__dict__
                    line_number= 1
                filename = globals.get('__file__')
                if filename:
                    fnl = filename.lower()
                    if fnl.endswith((".pyc", ".pyo")):
                        filename = filename[:-1]
                if filename:
                    # If there is no filename at all, the user is most likely in a REPL,
                    # and the warning is not necessary.
                    values = dict(
                        filename=filename,
                        line_number=line_number,
                        parser=builder.NAME,
                        markup_type=markup_type
                    )
                    warnings.warn(
                        self.NO_PARSER_SPECIFIED_WARNING % values,
                        GuessedAtParserWarning, stacklevel=2
                    )
        else:
            if kwargs:
                warnings.warn("Keyword arguments to the BeautifulSoup constructor will be ignored. These would normally be passed into the TreeBuilder constructor, but a TreeBuilder instance was passed in as `builder`.")
    
        self.builder = builder
        self.is_xml = builder.is_xml
        self.known_xml = self.is_xml
        self._namespaces = dict()
        self.parse_only = parse_only
    
        self.builder.initialize_soup(self)
    
        if hasattr(markup, 'read'):        # It's a file-type object.
            markup = markup.read()
>       elif len(markup) <= 256 and (
                (isinstance(markup, bytes) and not b'<' in markup)
                or (isinstance(markup, str) and not '<' in markup)
        ):
E       TypeError: object of type 'NoneType' has no len()

/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/bs4/__init__.py:312: TypeError
----------------------------- Captured stderr call -----------------------------
Warning: 2 09:04:27,944 [WARNING] kibitzr.notifier.factory: No notifications configured for 'Test page'
2021-10-12 09:04:27,945 [INFO] kibitzr.fetcher.loader: Fetching Test page at http://127.0.0.1:17261/form.html
127.0.0.1 - - [12/Oct/2021 09:04:27] "GET /form.html HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2021 09:04:28] "GET /params.html?name=aemn&pass=password HTTP/1.1" 200 -
------------------------------ Captured log call -------------------------------
WARNING  kibitzr.notifier.factory:factory.py:44 No notifications configured for 'Test page'
INFO     kibitzr.fetcher.loader:loader.py:37 Fetching Test page at http://127.0.0.1:17261/form.html
=============================== warnings summary ===============================
tests/simulation/test_fetcher.py::test_browser_xpath
  /home/runner/work/kibitzr/kibitzr/kibitzr/transformer/xpath.py:17: DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.
    from defusedxml import lxml as dlxml

tests/simulation/test_fetcher.py::test_scenario
  /home/runner/work/kibitzr/kibitzr/kibitzr/fetcher/browser/launcher.py:60: DeprecationWarning: use options instead of firefox_options
    firefox_options=firefox_options,

tests/simulation/test_fetcher.py::test_scenario
  /home/runner/work/kibitzr/kibitzr/kibitzr/fetcher/browser/fetcher.py:216: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    if isinstance(scenario, collections.Mapping):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED tests/simulation/test_forms.py::test_fill_form_sample - TypeError: obj...
=================== 1 failed, 74 passed, 3 warnings in 6.70s ===================
```

See #109

### CODE REVIEW

**Comment by egvimo** [comment]
Okay, looks like Travis CI has the same error. If you agree I would delete the `.travis.yml` file.

**Comment by peterdemin** [comment]
Looks good, thank you! Forms test seems to be flaky, I wonder if it surfaces an actual issue...
Let's keep `.travis.yml` for a little while.

**Comment by peterdemin** [comment]
Now I need to redirect the action to my DockerHub account.

**Comment by egvimo** [comment]
Yes, I've forgot to replace the Docker repository after the tests.

I'll create a new PR and add some other improvements.

**Pull request merged**
